[package]
name = "imgview"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
canopy = { version = "0.0.1", path = "../../crates/canopy" }
clap = { version = "4.5.53", features = ["derive"] }
image = "0.25.9"
thiserror = "2.0.17"

[lints]
workspace = true
