[package]
name = "canopy-geom"
authors = ["Aldo Cortesi <aldo@corte.si>"]
version = "0.0.1"
edition.workspace = true
license.workspace = true

[dependencies]
thiserror = "2.0.12"

[lints]
workspace = true
